export const ADD_MEMO = 'ADD_MEMO'
export const TOGGLE_MEMO = 'TOGGLE_MEMO'
export const INPUT_NAME = 'INPUT_NAME'
export const INPUT_COUNT = 'INPUT_COUNT'
export const CLEAR_INPUT = 'CLEAR_INPUT'
export const DELETE_MEMO = 'DELETE_MEMO'
export type ADD_MEMO_TYPE = typeof ADD_MEMO
export type TOGGLE_MEMO_TYPE = typeof TOGGLE_MEMO
export type INPUT_COUNT_TYPE = typeof INPUT_COUNT
export type INPUT_NAME_TYPE = typeof INPUT_NAME
export type CLEAR_INPUT_TYPE = typeof CLEAR_INPUT
